
name: Java build with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: cp 1
        run: echo "TRACER cp 1 `ls -l settings.gradle`"

      - name: cp 2
        run: echo "TRACER cp 2 `ls -l gradlew`"

      - name: cp 3
        run: ./gradlew --version

      # - name: run build script
      #   run: ./gradlew egg_1_max_p_threads:compileJava
