
name: Java test with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-gradle-groovy:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: run build script
        run: ./gradle-groovy-test.sh 
        working-directory: egg__12_sc_junit

  test-gradle-kotlin:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: run build script
        run: ./gradle-kotlin-test.sh 
        working-directory: egg__12_sc_junit

  test-maven:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.1
        with:
          java-version: 19
          maven-version: 3.8.6

      - name: run build script
        run: ./mvn-test.sh
        working-directory: egg__12_sc_junit

