
name: Java build with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
          with:
            distribution: 'zulu'
            java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: run build script
        run: ./gradle-build-all.sh 
